### ISSUE TITLE
ce faci bai? cum a fost la bacalaureat?

### ISSUE THREAD

**Issue by alexzanderr** [moonica13/testRepo#2]
iti dau issue pentru ca nu mai am numarul tau si voiam sa vad ce mai faci.

**Comment by moonica13** [comment]
Efectiv nu cred ca ai facut asta :))))))
A fost bine la bac, cam putin la mate dar asta este, o sa vad unde intru. 
9.60 fizica, 9.20 romana, 8.85 mate
